version: '3'

services:
  postgres:
    container_name: postgres_api_frete
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'abc123456'
      POSTGRES_DB: frete
    volumes:
      - ./data:/data/postgres
    ports:
      - '5432:5432'

  app:
    container_name: api_frete
    image: node
    command: bash -c "cd /usr/app && npm install && npm run dev"
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
